drop table if exists BIM_CONTENTS CASCADE;
create table BIM_CONTENTS (
 library_no bigint generated by default as identity NOT NULL,
 member_name varchar(255) NOT NULL,
 library_name varchar(70) NOT NULL,
 views int,
 regist_date varchar(255) NOT NULL,
 primary key (library_no)
);

drop table if exists IMG_PATH CASCADE;
create table IMG_PATH (
 library_file_no bigint generated by default as identity NOT NULL,
 library_no bigint NOT NULL,
 img_file_name varchar(255),

 primary key (library_file_no),
 foreign key (library_no) references BIM_CONTENTS(library_no)
);

insert into
BIM_CONTENTS(member_name, library_name, views, regist_date)
values('김민지', 'Terapod_Type_BPA ', 28, '2021-01-14');

insert into
BIM_CONTENTS(member_name, library_name, views, regist_date)
values('지아언니', 'Caisson_Type01_SIPA ', 94, '2020-11-14');

insert into
BIM_CONTENTS(member_name, library_name, views, regist_date)
values('대장님', 'Responsibility_TypeHAN_Africa', 10, '2019-08-30');

insert into
BIM_CONTENTS(member_name, library_name, views, regist_date)
values('누님', 'libraryName_Type_ICE', 15, '2021-06-30');

insert into
IMG_PATH (library_no, img_file_name)
values(1,'1.jpg');

insert into
IMG_PATH (library_no, img_file_name)
values(2,'2.jpg');

insert into
IMG_PATH (library_no, img_file_name)
values(3,'3.jpg');

insert into
IMG_PATH (library_no, img_file_name)
values(4,'4.jpg');




